export enum StorageKeys {
  LOCAL_USER_PK = "LOCAL_USER_PK",
  LOCAL_USER_ENCRYPTED_SK = "LOCAL_USER_ENCRYPTED_SK",
  SESSION_USER_SK = "SESSION_USER_SK",
  SESSION_USER_PASSCODE = "SESSION_USER_PASSCODE",
}
